pagination:
  enabled: true
  per_page: 4
  collection: "posts"
  permalink: "/blog/:num.html"
  # title: ':title - Page :num'
  indexpage: "/blog/index.html"
  debug: true
  limit: 0
  sort_field: "date"
  sort_reverse: true
url: https://mosaicmm.org

plugins:
  - jekyll-paginate-v2
  - jekyll-watch
  - jekyll-sitemap
  - jekyll-redirect-from
